L = []
A = L.append
A("@startuml")
A("' 图2-1 系统体系结构逻辑视图（当前实现）")
A("' 依据：docs/api/openapi.yaml 与当前代码（backend/internal、frontend/src）")
A("' 插入建议：横向整页（约 24cm 宽）时图内字号约 8pt，可读；若只放 14cm 正文栏，请把本图拆成上下两张")
A("")
A('skinparam defaultFontName "Microsoft YaHei"')
A("skinparam defaultFontSize 14")
A("skinparam shadowing false")
A("skinparam componentStyle rectangle")
A("skinparam packageStyle rectangle")
A("skinparam nodesep 18")
A("skinparam ranksep 30")
A("skinparam ArrowColor #46617A")
A("skinparam ArrowFontSize 12")
A("skinparam ArrowFontColor #2F3E4E")
A("skinparam componentBorderColor #1F4E79")
A("skinparam componentBackgroundColor #EEF4FA")
A("skinparam componentFontColor #10304C")
A("skinparam packageBorderColor #1F4E79")
A("skinparam packageFontColor #1F4E79")
A("skinparam noteBackgroundColor #FFF7E0")
A("skinparam noteBorderColor #B99A4A")
A("skinparam noteFontSize 12")
A("")
A("title 图2-1 系统体系结构逻辑视图（当前实现）")
A("")
A('package "① 客户端层（浏览器 · Vue 3 + TypeScript SPA）" as L1 {')
A('  component "Vue 3 SPA\\nDashboard.vue：创建表单与 idle/processing/ready/failed 三态\\nuseJourneyStore（Pinia）：快照与 20s 断线→15s 轮询回退\\nuseLocation 与 8 个展示/交互组件" as Client')
A('  component "api/journey.ts\\ncreateJourney / getState\\nupdateLocation / createStream" as ApiTs')
A("}")
A("")
A('package "② 接口层（Gin HTTP，统一前缀 /api/v1）" as L2 {')
A('  component "api.RegisterRoutes\\nPOST /journey\\nPOST /journey/{id}/location\\nGET /journey/{id}/state\\nGET /journey/{id}/stream" as Routes')
A('  component "api.JourneyHandler\\nCreate · UpdateLocation\\nState · Stream" as Handler')
A('  component "SSE 协议适配\\nretry: 5000\\nevent: snapshot / heartbeat(15s)" as SSEProto')
A("}")
A("")
A('package "③ 运行时编排层（单个 Go 进程）" as L3 {')
A('  component "runtime.Runtime\\n编排取数与决策、读写快照、订阅推送\\nCreateJourney · ApplyLocation · Recalculate\\nGetSnapshot · Subscribe · StartPeriodicRefresh" as Rt')
A('  component "并发与刷新策略\\nbusy.LoadOrStore 去重，不排队\\n单次分析超时 180s\\n每行程刷新间隔不小于 2min；终态跳过" as RtPolicy')
A("  note right of RtPolicy")
A("    位置或阶段更新后立即重算并推送，不等周期；")
A("    finish 先 SaveSnapshot 再 Publish")
A("  end note")
A("}")
A("")
A('package "④ Agent 与技能层（与 Runtime 同进程）" as L4 {')
A('  component "data.Agent\\nBuildState(ctx, Input{Journey, Progress})\\n缺失字段 → Registry.Query → 观测值校验\\n→ assessQuality：complete/degraded/unknown" as DataAgent')
A('  component "advice.Agent\\nEvaluate(ctx, Input{State, Progress, Issues,\\nAirportIATA, HasBaggage})\\n模型未配置或调用失败 → degraded(risk=unknown)" as AdviceAgent')
A('  component "skill.Registry\\nRegister(s) / Query(ctx, query)" as Registry')
A('  component "数据技能（skill.Skill 实现）\\nFlightIdentitySkill：EOOB 航班号搜索（5min 缓存）\\nFlightStatusSkill：EOOB 状态 JSON\\nAirportStatusSkill：EOOB 机场页与延误接口\\nRouteETASkill：直线距离×1.3÷30km/h（low）" as Skills')
A('  component "model.Client → model.OpenAI\\nChat(ctx, req)\\nOpenAI 兼容端点（百炼/vLLM/Ollama）" as ModelClient')
A("  note bottom of DataAgent")
A("    没有观测值的字段一律 null；单个 Skill 失败只追加 issue")
A("  end note")
A("  note bottom of AdviceAgent")
A("    关键数据缺失 → risk=unknown 并过滤带 Nav 的行动；")
A("    不执行改签、支付、叫车")
A("  end note")
A("}")
A("")
A('package "⑤ 存储与推送层（进程内，无数据库）" as L5 {')
A('  component "store.MemoryStore\\njourneys · snapshots · progress\\nRWMutex · 重启即丢失" as Ms')
A('  component "runtime.SSEHub\\nsubs · 缓冲 4 · 非阻塞 Publish\\nSubscribe(id) → (channel, cancel)" as Hub')
A("}")
A("")
A('package "⑥ 外部能力（进程外）" as L6 {')
A('  component "EOOB 聚合站点\\napil.eoob.com：航班搜索 / 状态 JSON\\nwww.eoob.com.cn：机场页 + delaybox\\n（v1 唯一航班与机场数据来源）" as EOOB')
A('  component "模型服务\\nOpenAI 兼容 API\\n未配置时整链路仍可运行" as LLM')
A('  component "高德 App / 网页\\namapuri:// 与 uri.amap.com\\n仅用户点击后打开" as Amap')
A('  component "mockserver（:8081）\\n开发期夹具：正常 / MU9999 / FAIL" as Mock')
A("}")
A("")
A("' ===== 关键协作关系（自左向右、自上而下为调用方向）=====")
A("Client --> ApiTs : 提交行程 / 触发定位")
A("ApiTs --> Routes : HTTP JSON（POST /journey、POST /location、GET /state）")
A("ApiTs --> SSEProto : EventSource 订阅 /stream")
A("Routes --> Handler : 路由分发")
A("Handler --> Rt : 调用 Runtime，不含 Agent 规则")
A("Rt --> DataAgent : BuildState(ctx, Input)")
A("Rt --> AdviceAgent : decide() 后 Evaluate(ctx, Input)\\n状态无实质变化时复用上一版建议")
A("Rt --> Ms : Save / Get Journey · Progress · Snapshot")
A("Rt --> Hub : Publish(id, snapshot)")
A("Hub --> Handler : snapshot channel → event: snapshot")
A("DataAgent --> Registry : Query(ctx, query)")
A("Registry --> Skills : Execute(ctx, query)")
A("AdviceAgent --> ModelClient : Chat(ctx, req)")
A("Skills --> EOOB : HTTPS JSON / HTML")
A("ModelClient --> LLM : HTTPS")
A("Client --> Amap : NavigateButton.open（App 优先，1.2s 回退 Web）")
A("Mock .up.> Routes : 开发联调时替代真实后端")
A("")
A("@enduml")
out = "\n".join(L) + "\n"
open(r"D:\VST DEVELOP\aviation-journey-agent\docs\uml\2-1_system_architecture.puml", "w", encoding="utf-8", newline="\n").write(out)
open(r"D:\VST DEVELOP\aviation-journey-agent\.docxwork\arch4.puml", "w", encoding="utf-8", newline="\n").write(out)
print("lines", len(L), "chars", len(out))
