L = []
A = L.append
A("@startuml")
A("' 图2-1 系统体系结构逻辑视图（当前实现）")
A("' 依据：docs/api/openapi.yaml 与当前代码（backend/internal、frontend/src）")
A("' 说明：图中只保留结构，各类的职责与边界见正文表 2-1")
A("' 插入建议：整页宽度（≥13cm）时图内字号约 8pt，可读")
A("")
A('skinparam defaultFontName "Microsoft YaHei"')
A("skinparam defaultFontSize 14")
A("skinparam shadowing false")
A("skinparam componentStyle rectangle")
A("skinparam packageStyle rectangle")
A("skinparam nodesep 20")
A("skinparam ranksep 34")
A("skinparam ArrowColor #46617A")
A("skinparam ArrowFontSize 12")
A("skinparam ArrowFontColor #2F3E4E")
A("skinparam componentBorderColor #1F4E79")
A("skinparam componentBackgroundColor #EEF4FA")
A("skinparam componentFontColor #10304C")
A("skinparam packageBorderColor #1F4E79")
A("skinparam packageFontColor #1F4E79")
A("skinparam noteBackgroundColor #FFF7E0")
A("skinparam noteBorderColor #B99A4A")
A("skinparam noteFontSize 12")
A("")
A("title 图2-1 系统体系结构逻辑视图（当前实现）")
A("")
A('package "① 客户端层（浏览器）" as L1 {')
A('  component "Vue 3 SPA\\nDashboard.vue\\nuseJourneyStore / useLocation" as Client')
A('  component "api/journey.ts\\ncreateJourney / getState\\nupdateLocation / createStream" as ApiTs')
A("}")
A("")
A('package "② 接口层（Gin，/api/v1）" as L2 {')
A('  component "api.JourneyHandler\\nCreate / UpdateLocation\\nState / Stream" as Handler')
A('  component "SSE 适配\\nretry 5000\\nsnapshot · heartbeat" as SSEProto')
A("}")
A("")
A('package "③ 运行时编排层（单个 Go 进程）" as L3 {')
A('  component "runtime.Runtime\\n编排取数与决策\\n快照读写 · 订阅推送" as Rt')
A('  component "并发与刷新策略\\nbusy 去重不排队\\n超时 180s · 每行程 2min" as RtPolicy')
A('  component "api.RegisterRoutes\\n4 条路由" as Routes')
A("  note bottom of RtPolicy")
A("    位置或阶段更新后立即重算并推送，");
A("    不等周期刷新；finish 先存快照再广播")
A("  end note")
A("}")
A("")
A('package "④ Agent 与技能层" as L4 {')
A('  component "data.Agent\\nBuildState：取数并评估质量" as DataAgent')
A('  component "advice.Agent\\nEvaluate：模型建议 + 风险下限" as AdviceAgent')
A('  component "skill.Registry\\nRegister / Query" as Registry')
A('  component "数据技能\\nFlightIdentity · FlightStatus\\nAirportStatus · RouteETA" as Skills')
A('  component "model.Client\\nmodel.OpenAI" as ModelClient')
A("  note bottom of DataAgent")
A("    没有观测值的字段一律 null；");
A("    单个 Skill 失败只记 issue")
A("  end note")
A("  note bottom of AdviceAgent")
A("    关键数据缺失 → risk=unknown");
A("    并过滤带 Nav 的行动")
A("  end note")
A("}")
A("")
A('package "⑤ 存储与推送层（进程内）" as L5 {')
A('  component "store.MemoryStore\\njourneys · snapshots\\nprogress" as Ms')
A('  component "runtime.SSEHub\\nsubs · 缓冲 4\\n非阻塞 Publish" as Hub')
A("}")
A("")
A('package "⑥ 外部能力（进程外）" as L6 {')
A('  component "EOOB 聚合站点\\n航班搜索 / 状态 JSON\\n机场页 + delaybox" as EOOB')
A('  component "模型服务\\nOpenAI 兼容 API" as LLM')
A('  component "高德 App / 网页\\namapuri:// 与 amapuri.com" as Amap')
A('  component "mockserver :8081\\n开发期夹具" as Mock')
A("}")
A("")
A("' ===== 协作关系 =====")
A("Client --> ApiTs : 提交行程 / 上报定位")
A("ApiTs --> Routes : HTTP JSON")
A("ApiTs --> SSEProto : EventSource")
A("Routes --> Handler : 路由分发")
A("Handler --> Rt : 调用 Runtime")
A("Rt --> DataAgent : BuildState(ctx, Input)")
A("Rt --> AdviceAgent : decide() 后 Evaluate")
A("Rt --> Ms : Save / Get 快照与进度")
A("Rt --> Hub : Publish(id, snapshot)")
A("Hub --> Handler : snapshot channel")
A("DataAgent --> Registry : Query(ctx, query)")
A("Registry --> Skills : Execute(ctx, query)")
A("AdviceAgent --> ModelClient : Chat(ctx, req)")
A("Skills --> EOOB : HTTPS")
A("ModelClient --> LLM : HTTPS")
A("Client --> Amap : 用户点击后打开")
A("Mock .up.> Routes : 开发联调替代后端")
A("")
A("@enduml")
out = "\n".join(L) + "\n"
open(r"D:\VST DEVELOP\aviation-journey-agent\.docxwork\arch5.puml", "w", encoding="utf-8", newline="\n").write(out)
print("chars", len(out))
