L = []
A = L.append
A("@startuml")
A("' 图2-1 系统体系结构逻辑视图（当前实现）")
A("' 约束：只描述分层与职责，不出现具体包名、类名、方法名")
A("' 依据：docs/api/openapi.yaml 与当前代码（backend/internal、frontend/src）")
A("")
A('skinparam defaultFontName "Microsoft YaHei"')
A("skinparam defaultFontSize 15")
A("skinparam shadowing false")
A("skinparam componentStyle rectangle")
A("skinparam packageStyle rectangle")
A("skinparam nodesep 18")
A("skinparam ranksep 30")
A("skinparam ArrowColor #46617A")
A("skinparam ArrowFontSize 12")
A("skinparam ArrowFontColor #2F3E4E")
A("skinparam componentBorderColor #1F4E79")
A("skinparam componentBackgroundColor #EEF4FA")
A("skinparam componentFontColor #10304C")
A("skinparam packageBorderColor #1F4E79")
A("skinparam packageFontColor #1F4E79")
A("skinparam noteBackgroundColor #FFF7E0")
A("skinparam noteBorderColor #B99A4A")
A("skinparam noteFontSize 12")
A("")
A("title 图2-1 系统体系结构逻辑视图（当前实现）")
A("")
A('package "① 客户端层（旅客界面）" as L1 {')
A('  component "行程创建\\n表单校验" as CForm')
A('  component "状态展示\\n时间轴·行动卡片" as CView')
A('  component "定位与阶段\\n位置上报" as CLoc')
A('  component "提醒与导航\\n点击后跳转" as CNav')
A("}")
A("")
A('package "② 接口层（HTTP 与实时通道）" as L2 {')
A('  component "创建行程接口\\n异步受理" as ICreate')
A('  component "位置/阶段接口\\n触发重算" as IUpdate')
A('  component "快照查询接口\\n只读" as IState')
A('  component "实时订阅通道\\n断线重连" as IStream')
A("  note bottom of IUpdate")
A("    开发期可用夹具后端替代真实后端，");
A("    提供正常 / 延误 / 失败三套场景")
A("  end note")
A("}")
A("")
A('package "③ 运行时编排层" as L3 {')
A('  component "行程编排\\n创建·更新·重算" as RLife')
A('  component "刷新与去重\\n单行程不排队" as RPolicy')
A("  note bottom of RPolicy")
A("    位置或阶段变化后立即重算并推送，");
A("    不等周期刷新；先存快照再广播")
A("  end note")
A("}")
A("")
A('package "④ 分析与决策层（双 Agent 协同）" as L4 {')
A('  component "数据感知 Agent\\n取数并评估质量" as AData')
A('  component "行动决策 Agent\\n阶段·风险·建议" as AAdvice')
A('  component "数据技能集合\\n航班·机场·路程" as ASkill')
A('  component "模型接入\\nOpenAI 兼容" as AModel')
A("}")
A("")
A('package "⑤ 存储与推送层" as L5 {')
A('  component "快照存储\\n进程内" as SStore')
A('  component "订阅与广播\\n全量快照" as SPush')
A("}")
A("")
A('package "⑥ 外部能力" as L6 {')
A('  component "航班与机场数据源\\n（聚合站点）" as XData')
A('  component "大模型服务" as XModel')
A('  component "地图导航应用/网页" as XMap')
A("}")
A("")
A("' ===== 协作关系 =====")
A("CForm --> ICreate : 提交行程")
A("CLoc --> IUpdate : 上报坐标或阶段")
A("CView --> IState : 拉取快照")
A("CView --> IStream : 订阅快照")
A("CNav --> XMap : 点击后打开")
A("ICreate --> RLife")
A("IUpdate --> RLife")
A("IState --> SStore : 读取")
A("IStream --> SPush : 订阅")
A("RLife --> AData : 先取数")
A("RLife --> AAdvice : 后决策")
A("RLife --> SStore : 保存")
A("RLife --> SPush : 广播")
A("AData --> ASkill : 按缺失字段调用")
A("ASkill --> XData : HTTPS")
A("AAdvice --> AModel : 生成建议")
A("AModel --> XModel : HTTPS")
A("SPush --> IStream : 推送")
A("")
A("@enduml")
out = "\n".join(L) + "\n"
path = r"D:\VST DEVELOP\aviation-journey-agent\docs\uml\2-1_system_architecture.puml"
open(path, "w", encoding="utf-8", newline="\n").write(out)
open(r"D:\VST DEVELOP\aviation-journey-agent\.docxwork\arch9.puml", "w", encoding="utf-8", newline="\n").write(out)
print("chars", len(out))
