L = []
A = L.append
A("@startuml")
A("' 图2-1 系统体系结构图（分层结构视图）")
A("' 画法：分层包 + 构造型类（boundary / control / entity / interface）+ 层间依赖")
A("' 名称均为概念名，不对应代码中的包名与类名")
A("")
A('skinparam defaultFontName "Microsoft YaHei"')
A("skinparam defaultFontSize 15")
A("skinparam shadowing false")
A("skinparam classAttributeIconSize 0")
A("skinparam packageStyle rectangle")
A("skinparam nodesep 26")
A("skinparam ranksep 42")
A("skinparam ArrowColor #333333")
A("skinparam ArrowFontSize 12")
A("skinparam classBackgroundColor #FFFFFF")
A("skinparam classBorderColor #1F1F1F")
A("skinparam classFontColor #111111")
A("skinparam packageBorderColor #1F1F1F")
A("skinparam packageFontColor #111111")
A("")
A("title 图2-1 系统体系结构图")
A("")
A("' ==================== 用户界面层 ====================")
A('package "用户界面层" as L1 {')
A('  class "行程创建界面类" as UI1 <<boundary>> {')
A("    +录入航班与行李信息()")
A("    +提交行程()")
A("  }")
A('  class "行程状态界面类" as UI2 <<boundary>> {')
A("    +展示状态与时间轴()")
A("    +展示行动建议()")
A("  }")
A('  class "定位与阶段确认界面类" as UI3 <<boundary>> {')
A("    +上报当前位置()")
A("    +确认所处阶段()")
A("  }")
A("}")
A("")
A("' ==================== 业务逻辑层 ====================")
A('package "业务逻辑层" as L2 {')
A('  class "行程编排控制类" as B1 <<control>> {')
A("    -行程标识")
A("    +创建行程()")
A("    +更新位置或阶段()")
A("    +触发重算()")
A("  }")
A('  class "数据感知控制类" as B2 <<control>> {')
A("    +获取航班与机场数据()")
A("    +校验观测数据()")
A("    +评估数据质量()")
A("  }")
A('  class "行动决策控制类" as B3 <<control>> {')
A("    +分析阶段与风险()")
A("    +生成行动建议()")
A("    +执行风险下限()")
A("  }")
A('  class "快照与推送控制类" as B4 <<control>> {')
A("    +保存完整快照()")
A("    +广播完整快照()")
A("  }")
A("}")
A("")
A("' 业务逻辑层右侧：快照实体与其读写接口（对应参考图中的实体类 + 接口圆）")
A('class "行程快照实体类" as E0 <<entity>> {')
A("  -分析状态")
A("  -生成时间")
A("  -数据质量")
A("}")
A('interface "快照读写接口" as ISnap')
A("")
A("' ==================== 数据层 ====================")
A('package "数据层" as L3 {')
A('  class "行程实体类" as E1 <<entity>> {')
A("    -行程标识")
A("    -是否托运行李")
A("  }")
A('  class "航段实体类" as E2 <<entity>> {')
A("    -航班号")
A("    -出行日期")
A("    -出发机场")
A("    -到达机场")
A("  }")
A('  class "行程状态实体类" as E3 <<entity>> {')
A("    -航班状态")
A("    -时间轴节点")
A("    -预计路程时长")
A("    -数据质量")
A("  }")
A('  class "位置进度实体类" as E4 <<entity>> {')
A("    -经度")
A("    -纬度")
A("    -手动确认阶段")
A("  }")
A("}")
A("")
A("' ==================== 设备接口层 ====================")
A('package "设备接口层" as L4 {')
A('  interface "聚合数据源接口" as I1')
A('  interface "大模型接口" as I2')
A('  interface "地图导航接口" as I3')
A("}")
A("")
A("' ==================== 外部系统 ====================")
A('class "航班与机场数据来源" as X1 <<external>>')
A('class "大模型服务" as X2 <<external>>')
A('class "地图导航应用或网页" as X3 <<external>>')
A("")
A("' ==================== 层间依赖 ====================")
A("UI1 ..> B1 : 调用")
A("UI2 ..> B1 : 调用")
A("UI3 ..> B1 : 调用")
A("UI2 ..> B4 : 订阅实时快照")
A("UI3 ..> I3 : 用户点击后跳转")
A("B1 ..> B2 : 请求取数")
A("B1 ..> B3 : 请求决策")
A("B1 ..> B4 : 提交快照")
A("B2 ..> B4 : 观测结果")
A("B3 ..> B4 : 建议结果")
A("B2 ..> I1 : 使用")
A("B3 ..> I2 : 使用")
A("I1 -- X1")
A("I2 -- X2")
A("I3 -- X3")
A("")
A("' ==================== 与数据层、实体的关系 ====================")
A("B1 ..> E1 : 读取行程")
A("B1 ..> E4 : 读写位置与阶段")
A("B2 ..> E3 : 写入行程状态")
A("B4 ..> E0 : 保存与读取快照")
A("B4 -up- ISnap")
A("E0 ..> ISnap : 实现")
A("E1 \"1\" *-- \"1..*\" E2 : 包含航段")
A("E0 \"1\" *-- \"1\" E3 : 包含状态")
A("E0 \"1\" *-- \"1\" E4 : 包含进度")
A("")
A("' ==================== 体系结构约束 ====================")
A("note top of L1")
A("  只负责展示与上报，不计算风险、不推断旅客阶段")
A("end note")
A("note bottom of L2")
A("  业务逻辑层是唯一编排者：先取数、后决策，");
A("  失败只降级不中断；不执行改签、支付、叫车等操作")
A("end note")
A("note bottom of L3")
A("  课程版为进程内存储，进程重启数据丢失，不支持多实例共享")
A("end note")
A("note bottom of L4")
A("  外部数据只经接口层进入系统；未配置大模型时系统仍可运行")
A("end note")
A("")
A("@enduml")
out = "\n".join(L) + "\n"
open(r"D:\VST DEVELOP\aviation-journey-agent\docs\uml\2-1_system_architecture.puml", "w", encoding="utf-8", newline="\n").write(out)
print("written", len(out), "chars,", len(L), "lines")
