# -*- coding: utf-8 -*-
lines = []
A = lines.append
A("@startuml")
A("' 图2-1 系统体系结构逻辑视图（当前实现）")
A("' 依据：docs/api/openapi.yaml 与当前代码（backend/internal、frontend/src）")
A("' 插入建议：横向整页或单独一页，保证图内字号缩放后不小于 7pt")
A("")
A('skinparam defaultFontName "Microsoft YaHei"')
A("skinparam defaultFontSize 14")
A("skinparam shadowing false")
A("skinparam componentStyle rectangle")
A("skinparam packageStyle rectangle")
A("skinparam nodesep 14")
A("skinparam ranksep 26")
A("skinparam ArrowColor #46617A")
A("skinparam ArrowFontSize 12")
A("skinparam ArrowFontColor #2F3E4E")
A("skinparam componentBorderColor #1F4E79")
A("skinparam componentBackgroundColor #EEF4FA")
A("skinparam componentFontColor #10304C")
A("skinparam packageBorderColor #1F4E79")
A("skinparam packageFontColor #1F4E79")
A("skinparam noteBackgroundColor #FFF7E0")
A("skinparam noteBorderColor #B99A4A")
A("skinparam noteFontSize 12")
A("")
A("title 图2-1 系统体系结构逻辑视图（当前实现）")
A("")
A("' ===== ① 客户端层 =====")
A('package "① 客户端层（浏览器 · Vue 3 + TypeScript SPA，独立 Vite 工程）" as L1 {')
A('  component "Dashboard.vue\n创建行程表单；idle / processing / ready / failed 三态渲染\nfailed 用 lastReady 保留已有内容" as Dashboard')
A('  component "useJourneyStore（Pinia）\nsnapshot · lastReady · connected · fallbackActive\nload / stop / apply / pollState；断线 20s 后每 15s 轮询 /state" as JStore')
A('  component "useLocation\n浏览器 Geolocation；六类手动阶段降级入口" as ULoc')
A('  component "展示与交互组件\nStatusBar · FreshnessBar · MetricsRow · Timeline\nActionCardList · NavigateButton · StageConfirm · ToastHost" as WComp')
A('  component "api/journey.ts（axios + EventSource，baseURL /api/v1）\ncreateJourney / getState / updateLocation / createStream" as ApiTs')
A("}")
A("")
A("' ===== ② 接口层 =====")
A('package "② 接口层（Gin HTTP，统一前缀 /api/v1）" as L2 {')
A('  component "api.JourneyHandler\n+ Create(c) · UpdateLocation(c) · State(c) · Stream(c)" as Handler')
A('  component "api.RegisterRoutes\nPOST /journey · POST /journey/{id}/location\nGET /journey/{id}/state · GET /journey/{id}/stream" as Routes')
A('  component "SSE 协议适配\nretry: 5000 · event: snapshot / heartbeat(15s)\nCache-Control: no-cache · X-Accel-Buffering: no" as SSEProto')
A("  note right of Handler")
A("    400 参数错误 / 404 行程不存在 / 500 未预期错误；")
A("    分析失败不返回 5xx，而是产出 status=failed 的快照")
A("  end note")
A("}")
A("")
A("' ===== ③ 运行时编排层 =====")
A('package "③ 运行时编排层（单个 Go 进程，进程内编排）" as L3 {')
A('  component "runtime.Runtime\n- store / data / advice / hub / busy: sync.Map\n+ CreateJourney · ApplyLocation · Recalculate\n+ GetSnapshot · Subscribe · StartPeriodicRefresh\n- decide · finish · publishProcessing · analyzeAsync · previousSnapshot" as Rt')
A('  component "编排与并发策略\nbusy.LoadOrStore 去重：同行程并发重算直接返回当前快照，不排队\n单次分析超时 180s；StartPeriodicRefresh 15s 轮询\n每行程刷新间隔不小于 2min；已起飞/取消或出发日期已过则跳过" as RtPolicy')
A("  note right of RtPolicy")
A("    位置或阶段更新后立即重算并经 SSEHub 推送，");
A("    不等周期刷新；finish 先 SaveSnapshot 再 Publish")
A("  end note")
A("}")
A("")
A("' ===== ④ Agent 与技能层 =====")
A('package "④ Agent 与技能层（与 Runtime 同一 Go 进程）" as L4 {')
A('  component "data.Agent\n+ BuildState(ctx, Input{Journey, Progress}) → Result{State, Journey, Issues}\n缺失字段 → Registry.Query → applyObservations（类型/枚举/RFC3339 校验）\n→ assessQuality → complete / degraded / unknown" as DataAgent')
A('  component "advice.Agent\n+ Evaluate(ctx, Input{State, Progress, Issues, AirportIATA, HasBaggage}) → Advice\n- evaluate · - degraded · enforceRiskFloor 风险下限" as AdviceAgent')
A('  component "skill.Registry\n+ Register(s) · + Query(ctx, query)\n一个技能支持多字段只调用一次；无技能支持则记 issue" as Registry')
A('  component "skill.Skill（接口）\n+ Name() · + Supports(field) · + Execute(ctx, query)" as SkillIface')
A('  component "FlightIdentitySkill\nEOOB 航班号搜索 JSON（5min 缓存）\n补全缺失的日期与航线" as SkIdentity')
A('  component "FlightStatusSkill\nEOOB 航班状态 JSON\n航班状态 / 时间轴 / 登机口" as SkStatus')
A('  component "AirportStatusSkill\nEOOB 机场页 HTML 与 /api/delaybox/{IATA}\nUA 与 Sec-CH-UA 版本同源；20s 超时" as SkAirport')
A('  component "RouteETASkill\nHaversine 直线距离 ×1.3 ÷ 30km/h\n本地估算，confidence=low，traffic 保持 null" as SkEta')
A('  component "model.Client（接口）\n+ Chat(ctx, req) (Response, error)" as ModelClient')
A('  component "model.OpenAI\nOpenAI 兼容端点（百炼 / vLLM / Ollama）" as ModelOpenAI')
A("  note bottom of DataAgent")
A("    没有观测值的字段一律 null，不用默认值填充；")
A("    单个 Skill 失败只追加 issue，不伪造观测值")
A("  end note")
A("  note bottom of AdviceAgent")
A("    模型未配置 / 调用失败 / 枚举非法 → degraded（risk=unknown）；")
A("    关键数据缺失 → risk=unknown 并过滤带 Nav 的行动；")
A("    不执行改签、支付、叫车")
A("  end note")
A("}")
A("")
A("' ===== ⑤ 存储与推送层 =====")
A('package "⑤ 存储与推送层（进程内，无数据库）" as L5 {')
A('  component "store.MemoryStore\n- mu: sync.RWMutex · journeys · snapshots · progress\n+ SaveJourney / GetJourney · SaveSnapshot / GetSnapshot\n+ SaveProgress / GetProgress · ListJourneyIDs" as Ms')
A('  component "runtime.SSEHub\n- mu · subs: map[journeyId]map[chan]struct\n+ Subscribe(id) → (channel, cancel) · + Publish(id, snapshot)\n缓冲深度 4；慢订阅者丢弃该帧" as Hub')
A("  note right of Ms")
A("    进程重启数据即丢失，不支持多实例；")
A("    快照是 REST /state 与 SSE 的唯一数据源")
A("  end note")
A("}")
A("")
A("' ===== ⑥ 外部能力 =====")
A('package "⑥ 外部能力（进程外；v1 航班与机场数据只来自 EOOB）" as L6 {')
A('  component "EOOB 聚合站点\napil.eoob.com：航班号搜索 JSON、航班状态 JSON\nwww.eoob.com.cn：机场页 HTML、/api/delaybox/{IATA}" as EOOB')
A('  component "模型服务\nOpenAI 兼容 API；未配置时整条链路仍可运行" as LLM')
A('  component "高德 App / 网页\namapuri://route/plan 与 uri.amap.com\n仅用户点击后打开，不采集轨迹" as Amap')
A('  component "mockserver（开发期夹具，:8081）\n正常 / MU9999 延误+登机口变更 / FAIL 分析失败" as Mock')
A("}")
A("")
A("' ===== 关系 =====")
A("Dashboard --> ApiTs : submit / retry")
A("JStore --> ApiTs : getState / createStream")
A("ULoc --> ApiTs : updateLocation(lat,lng) 或 (stage)")
A("WComp --> JStore : 只渲染 snapshot，不做业务计算")
A("WComp --> Amap : NavigateButton.open\nApp 优先，1.2s 回退 Web")
A("ApiTs --> Handler : HTTP JSON（POST /journey、POST /location、GET /state）")
A("ApiTs --> SSEProto : EventSource 订阅 /stream")
A("SSEProto --> Handler")
A("Routes --> Handler")
A("Handler --> Rt : 调用 Runtime，不含 Agent 规则")
A("Rt --> DataAgent : BuildState(ctx, Input)")
A("Rt --> AdviceAgent : decide() 后 Evaluate(ctx, Input)\n状态无实质变化时复用上一版建议")
A("Rt --> Ms : Save / Get Journey · Progress · Snapshot")
A("Rt --> Hub : Publish(id, snapshot)")
A("Hub --> Handler : snapshot channel → event: snapshot")
A("DataAgent --> Registry : Query(ctx, query)")
A("Registry --> SkillIface : Execute(ctx, query)")
A("SkillIface <|.. SkIdentity")
A("SkillIface <|.. SkStatus")
A("SkillIface <|.. SkAirport")
A("SkillIface <|.. SkEta")
A("SkIdentity --> EOOB : HTTPS JSON")
A("SkStatus --> EOOB : HTTPS JSON")
A("SkAirport --> EOOB : HTTPS HTML / JSON")
A("AdviceAgent --> ModelClient : Chat(ctx, req)")
A("ModelOpenAI ..|> ModelClient")
A("ModelClient --> LLM : HTTPS")
A("SkEta ..> ULoc : 使用前端上报的坐标\n（经 Handler → Runtime → DataAgent 传入）")
A("Mock .up.> Handler : 开发联调时替代真实后端")
A("")
A("@enduml")
out = "\n".join(lines) + "\n"
open(r"D:\VST DEVELOP\aviation-journey-agent\docs\uml\2-1_system_architecture.puml", "w", encoding="utf-8", newline="\n").write(out)
open(r"D:\VST DEVELOP\aviation-journey-agent\.docxwork\arch2.puml", "w", encoding="utf-8", newline="\n").write(out)
print("written", len(out), "chars")
