L = []
A = L.append
A("@startuml")
A("' 图2-1 系统体系结构图（分层逻辑视图 · 当前实现）")
A("' 说明：只描述分层、构件与依赖方向，不出现具体包名、类名、方法名")
A("' 对齐：docs/03 的边界类 / 控制类 / 实体类划分与 4 个旅客用例")
A("")
A('skinparam defaultFontName "Microsoft YaHei"')
A("skinparam defaultFontSize 16")
A("skinparam shadowing false")
A("skinparam componentStyle rectangle")
A("skinparam packageStyle rectangle")
A("skinparam nodesep 20")
A("skinparam ranksep 34")
A("skinparam ArrowColor #46617A")
A("skinparam ArrowFontSize 13")
A("skinparam ArrowFontColor #2F3E4E")
A("skinparam componentBorderColor #1F4E79")
A("skinparam componentBackgroundColor #EEF4FA")
A("skinparam componentFontColor #10304C")
A("skinparam packageBorderColor #1F4E79")
A("skinparam packageFontColor #1F4E79")
A("skinparam noteBackgroundColor #FFF7E0")
A("skinparam noteBorderColor #B99A4A")
A("skinparam noteFontSize 13")
A("")
A("title 图2-1 系统体系结构图（分层逻辑视图）")
A("")
A("' ==================== 表示层 ====================")
A('package "表示层 · 旅客界面（浏览器内运行）" as P1 {')
A('  component "行程创建界面\\n录入航班与行李信息" as ViewCreate')
A('  component "行程状态界面\\n状态·时间轴·行动卡片" as ViewState')
A('  component "定位与阶段确认界面\\n浏览器定位或手动确认" as ViewLocate')
A('  component "提醒与导航入口\\n用户确认后跳转" as ViewNav')
A("}")
A("")
A("' ==================== 接口层 ====================")
A('package "接口层 · 请求接入与实时通道" as P2 {')
A('  interface "行程管理接口" as IfJourney')
A('  interface "实时快照通道" as IfStream')
A('  component "请求校验与协议适配\\n参数校验·状态码·事件帧" as Gateway')
A("}")
A("")
A("' ==================== 应用编排层 ====================")
A('package "应用编排层 · 单进程内编排" as P3 {')
A('  component "行程生命周期编排\\n创建·更新·触发重算" as Orchestrator')
A('  component "重算调度与并发控制\\n同行程不排队，终态不再刷新" as Scheduler')
A('  component "快照协调\\n保存完整快照并立即推送" as SnapshotCoord')
A("  note right of Scheduler")
A("    位置或阶段变化后立即重算并推送；");
A("    分析失败产出失败态快照，不向前端返回故障")
A("  end note")
A("}")
A("")
A("' ==================== 领域服务层 ====================")
A('package "领域服务层 · 双 Agent 协同" as P4 {')
A('  component "数据感知 Agent\\n按缺失字段取数，只产出有依据的数据" as DataAgent')
A('  component "行动决策 Agent\\n生成阶段·风险·提醒·行动建议" as AdviceAgent')
A('  component "数据技能集合\\n航班身份·航班状态·机场信息·路程估算" as Skills')
A('  component "模型接入\\n兼容通用大模型接口" as ModelPort')
A("  note bottom of DataAgent")
A("    没有依据的字段保持未知；单个数据来源失败");
A("    只记录问题，不影响其余字段返回")
A("  end note")
A("  note bottom of AdviceAgent")
A("    关键数据缺失时不得给出安全结论；");
A("    不执行改签、支付、叫车等高影响操作")
A("  end note")
A("}")
A("")
A("' ==================== 数据层 ====================")
A('package "数据访问层 · 进程内存储" as P5 {')
A('  component "行程与快照存储\\n行程·快照·位置进度" as Store')
A('  component "订阅与广播\\n按行程推送全量快照" as Broadcaster')
A("  note right of Store")
A("    课程版不引入数据库，进程重启数据丢失，");
A("    不支持多实例共享")
A("  end note")
A("}")
A("")
A("' ==================== 外部系统层 ====================")
A('package "外部系统层" as P6 {')
A('  component "航班与机场数据来源\\n统一聚合站点，不抓取航司官网" as ExtData')
A('  component "大模型服务\\n未配置时链路仍可运行" as ExtModel')
A('  component "地图导航应用／网页\\n只跳转，不采集轨迹" as ExtMap')
A("}")
A("")
A("' ==================== 层间依赖关系 ====================")
A("ViewCreate --> IfJourney : 创建行程")
A("ViewState --> IfJourney : 查询快照")
A("ViewState --> IfStream : 订阅实时快照")
A("ViewLocate --> IfJourney : 上报位置或阶段")
A("ViewNav --> ExtMap : 用户点击后打开")
A("IfJourney --> Gateway")
A("IfStream --> Gateway")
A("Gateway --> Orchestrator : 受理请求")
A("Orchestrator --> Scheduler : 触发重算")
A("Orchestrator --> SnapshotCoord : 生成快照")
A("Orchestrator --> DataAgent : 先取数")
A("Orchestrator --> AdviceAgent : 后决策")
A("Orchestrator --> Store : 读写行程与进度")
A("SnapshotCoord --> Store : 保存完整快照")
A("SnapshotCoord --> Broadcaster : 广播完整快照")
A("Broadcaster --> IfStream : 推送快照")
A("DataAgent --> Skills : 按缺失字段调用")
A("Skills --> ExtData : HTTPS 取数")
A("AdviceAgent --> ModelPort : 生成建议")
A("ModelPort --> ExtModel : HTTPS 调用")
A("")
A("' ==================== 架构约束 ====================")
A("note top of P1")
A("    只做展示与上报，不计算风险、不推断阶段");
A("end note")
A("note bottom of P4")
A("    领域服务只依赖上游传入的行程状态，");
A("    不直接访问外部数据来源与存储");
A("end note")
A("")
A("@enduml")
out = "\n".join(L) + "\n"
open(r"D:\VST DEVELOP\aviation-journey-agent\docs\uml\2-1_system_architecture.puml", "w", encoding="utf-8", newline="\n").write(out)
print("written", len(out), "chars")
