/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/journey": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 创建行程
         * @description 创建行程并触发一次分析。分析涉及大模型与外部数据技能，耗时较长，因此不阻塞等待。
         *     客户端不上报当前时间，服务端以收到请求的时刻为准。
         */
        post: operations["createJourney"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journey/{id}/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 上报位置或手动确认阶段
         * @description 两种用法，至少提供一种：
         *
         *     1. 上报定位坐标：传 lat + lng，必须成对出现。
         *        上报坐标会清除此前手动确认的阶段，以定位为准。
         *
         *     2. 手动确认阶段：传 stage，不传坐标。
         *        用于定位不可用或机场内定位不准时，由旅客自己确认所处阶段。
         *        手动确认后阶段保持不变，直到下一次上报坐标。
         *
         *     两种方式都会触发重算，并在完成后立即通过 SSE 推送新快照。
         */
        post: operations["updateLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journey/{id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询当前快照
         * @description 前端的唯一状态来源。返回结构与 SSE 推送的 data 完全一致。
         */
        get: operations["getJourneyState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journey/{id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 订阅行程快照（SSE）
         * @description 推送约定：
         *     1. 连接建立后立即推送一条 event: snapshot。
         *     2. 快照变化时推送 event: snapshot，data 结构与 /state 完全一致。
         *     3. 位置或阶段更新并重算完成后立即推送，不等下一个周期。
         *     4. 无变化时每 15 秒推送 event: heartbeat。
         *     5. 事件名固定为 snapshot / heartbeat，新增事件名属于破坏性变更。
         */
        get: operations["streamJourney"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateJourneyRequest: {
            /** @description 按行程顺序排列。v1 只处理第一个航段 */
            flights: components["schemas"]["Flight"][];
            /** @description 是否携带托运行李 */
            hasBaggage: boolean;
        };
        Flight: {
            /**
             * @description 航班号，统一大写不含空格
             * @example CA1234
             */
            number: string;
            /**
             * Format: date
             * @example 2026-09-11
             */
            date: string;
            /**
             * @description 出发机场 IATA 三字码
             * @example PVG
             */
            from: string;
            /**
             * @description 到达机场 IATA 三字码
             * @example PEK
             */
            to: string;
        };
        /**
         * @description 至少提供 lat + lng 或 stage 之一，否则返回 400。
         *     lat 与 lng 必须成对出现。
         */
        UpdateLocationRequest: {
            /** Format: double */
            lat?: number | null;
            /** Format: double */
            lng?: number | null;
            /** @description 旅客手动确认的当前阶段；上报坐标时会自动清除 */
            stage?: components["schemas"]["ManualStage"] | null;
        };
        AnalysisAccepted: {
            journeyId: string;
            status: components["schemas"]["AnalysisStatus"];
        };
        /** @description 前端唯一数据源。所有字段始终输出，未知值为 null */
        JourneySnapshot: {
            status: components["schemas"]["AnalysisStatus"];
            journey: components["schemas"]["Journey"];
            state: components["schemas"]["State"];
            advice: components["schemas"]["Advice"];
            /** @description 仅当 status = failed 时返回，面向旅客展示的一句话 */
            error?: string | null;
        };
        Journey: {
            id: string;
            flights: components["schemas"]["Flight"][];
            hasBaggage: boolean;
        };
        /** @description DataAgent 输出。只包含有依据的数据，没有依据的字段一律为 null */
        State: {
            flightStatus: components["schemas"]["FlightStatus"];
            gate: string | null;
            /** @description 时间轴节点，后端决定展示哪几个，已按时间升序排列 */
            timeline: components["schemas"]["TimelineNode"][];
            /** @description 当前位置到机场的预计耗时（分钟） */
            etaMin: number | null;
            traffic: components["schemas"]["Traffic"] | null;
            /** @description 机场内逐段文字指引，前端按数组顺序展示 */
            guide: string[];
            quality: components["schemas"]["Quality"];
            /**
             * Format: date-time
             * @description 快照生成时间。前端可用它校正本地时钟后再做倒计时
             */
            updatedAt: string;
        };
        TimelineNode: {
            /**
             * @description 节点名称，由后端生成
             * @example 开始登机
             */
            label: string;
            /**
             * Format: date-time
             * @description 节点时间，RFC3339，供前端做倒计时
             */
            time: string;
        };
        /** @description AdviceAgent 输出。只做判断与呈现，不重复 State 里的原始状态 */
        Advice: {
            stage: components["schemas"]["Stage"];
            risk: components["schemas"]["Risk"];
            /** @description 当前最该提醒旅客的一句话。null 表示无需提醒 */
            alert: string | null;
            /** @description 指标卡，是所有展示数字的唯一来源。value 已格式化 */
            cards: components["schemas"]["Card"][];
            /** @description 行动卡片，已按优先级排序 */
            actions: components["schemas"]["Action"][];
            /** @description 判断依据，含数据来源与时间 */
            reasons: string[];
        };
        Card: {
            /** @example 剩余缓冲 */
            label: string;
            /**
             * @description 已格式化的展示值，例如 "18 分钟"、"13:28"
             * @example 18 分钟
             */
            value: string;
        };
        Action: {
            /**
             * @description 稳定标识，如 leave_now
             * @example leave_now
             */
            id: string;
            /** @example 尽快出发 */
            title: string;
            /** @example 当前路况拥堵，预计 52 分钟到达机场 */
            detail: string;
            /** @description 有值时才渲染导航按钮 */
            nav?: components["schemas"]["Nav"] | null;
        };
        Nav: {
            /** @description 应用内跳转地址，优先使用 */
            app: string;
            /** @description 应用未安装时的网页兜底地址 */
            web: string;
        };
        Error: {
            /** @description 面向旅客或开发者的一句话，前端直接展示 */
            error: string;
        };
        /** @enum {string} */
        AnalysisStatus: "processing" | "ready" | "failed";
        /** @enum {string} */
        Stage: "unknown" | "en_route" | "at_airport" | "check_in" | "security" | "waiting" | "boarding" | "departed" | "disrupted";
        /**
         * @description 旅客可手动确认的阶段，是 Stage 的子集
         * @enum {string}
         */
        ManualStage: "en_route" | "at_airport" | "check_in" | "security" | "waiting" | "boarding";
        /**
         * @description unknown 表示关键数据缺失，前端不得渲染成绿色
         * @enum {string}
         */
        Risk: "unknown" | "green" | "yellow" | "orange" | "red";
        /** @enum {string} */
        Quality: "complete" | "degraded" | "unknown";
        /** @enum {string} */
        Traffic: "unknown" | "light" | "moderate" | "heavy" | "severe";
        /** @enum {string} */
        FlightStatus: "unknown" | "scheduled" | "on_time" | "delayed" | "boarding" | "departed" | "cancelled" | "diverted";
    };
    responses: {
        /** @description 请求参数不合法 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 行程不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 服务端错误 */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description 行程 ID，不透明字符串，客户端不得解析其结构 */
        JourneyId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createJourney: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "flights": [
                 *         {
                 *           "number": "CA1234",
                 *           "date": "2026-09-11",
                 *           "from": "PVG",
                 *           "to": "PEK"
                 *         }
                 *       ],
                 *       "hasBaggage": true
                 *     }
                 */
                "application/json": components["schemas"]["CreateJourneyRequest"];
            };
        };
        responses: {
            /** @description 已受理，分析进行中 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["ServerError"];
        };
    };
    updateLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 行程 ID，不透明字符串，客户端不得解析其结构 */
                id: components["parameters"]["JourneyId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLocationRequest"];
            };
        };
        responses: {
            /** @description 已受理，正在重算 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getJourneyState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 行程 ID，不透明字符串，客户端不得解析其结构 */
                id: components["parameters"]["JourneyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前快照，status 可能为 processing / ready / failed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneySnapshot"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    streamJourney: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 行程 ID，不透明字符串，客户端不得解析其结构 */
                id: components["parameters"]["JourneyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example retry: 5000
                     *
                     *     event: snapshot
                     *     data: {"status":"processing","journey":{...},"state":{...},"advice":{...}}
                     *
                     *     event: heartbeat
                     *     data: {"at":"2026-09-11T12:36:15+08:00"}
                     */
                    "text/event-stream": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
